# Generated by Django 4.2.13 on 2024-06-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_remove_agodadata_username_agodadata_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agodadata',
            name='currency',
            field=models.CharField(default='JPY', max_length=50),
        ),
        migrations.AlterField(
            model_name='agodadata',
            name='link_url',
            field=models.URLField(max_length=350),
        ),
        migrations.AlterField(
            model_name='agodadata',
            name='photo_url',
            field=models.URLField(max_length=350),
        ),
    ]
