# Generated by Django 4.2.13 on 2024-06-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_agodadata_currency_alter_agodadata_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agodadata',
            name='link_url',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='agodadata',
            name='photo_url',
            field=models.URLField(max_length=600),
        ),
    ]
